# Generated by Django 2.2.7 on 2021-01-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_applicationresponse_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationform',
            options={'ordering': ['deadline']},
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='release_date',
            field=models.DateTimeField(auto_now=True, verbose_name='release_date'),
        ),
    ]
