# Generated by Django 2.2.7 on 2021-01-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_auto_20210105_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_1', models.CharField(max_length=100, null=True, verbose_name='choice 1')),
                ('choice_2', models.CharField(max_length=100, null=True, verbose_name='choice 1')),
                ('choice_3', models.CharField(max_length=100, null=True, verbose_name='choice 1')),
                ('choice_4', models.CharField(max_length=100, null=True, verbose_name='choice 1')),
            ],
        ),
        migrations.AlterModelOptions(
            name='applicationform',
            options={'ordering': ['-release_date']},
        ),
    ]
