# Generated by Django 2.2.7 on 2021-01-09 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_auto_20210110_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='broker.QuestionChoices'),
        ),
    ]
