# Generated by Django 2.2.7 on 2021-01-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_question_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
    ]
