# Generated by Django 2.2.7 on 2021-01-09 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_remove_question_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoices',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='broker.Question'),
        ),
    ]
