# Generated by Django 2.2.7 on 2019-12-09 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='enterance_year',
            new_name='entrance_year',
        ),
    ]
