# Generated by Django 2.2.7 on 2019-12-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20191209_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('ce', 'Computer Engineering'), ('cs', 'Conputer Science'), ('ee', 'Electrical Engineering')], max_length=2, null=True),
        ),
    ]
