# Generated by Django 2.2.7 on 2020-02-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20191222_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='rank',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
