# Generated by Django 2.2.7 on 2020-02-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200207_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='rank',
            field=models.CharField(choices=[('AOP', 'Associate Professor'), ('AIP', 'Assistant Professor'), ('P', 'Professor')], max_length=20, null=True),
        ),
    ]
