# Generated by Django 2.2.7 on 2020-02-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200207_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='rank',
            field=models.CharField(choices=[('AO', 'Associate Professor'), ('AI', 'Assistant Professor'), ('PR', 'Professor')], max_length=20, null=True),
        ),
    ]
